#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

mkdir -p bin
[ "$(uname)" != "Darwin" ] && LINKFLAGS="-linkmode external -extldflags -static -s"

CGO_ENABLED=0 go build -ldflags "-X main.VERSION=$VERSION $LINKFLAGS" -o bin/kontainer-engine-example-driver
echo built default
for i in darwin linux
do
    export GOOS=$i
    go build -o bin/kontainer-engine-example-driver-$i
    echo built $i
done
